services:
  - type: web
    name: argfy-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
      mkdir -p backend/data
      cd backend && python scripts/init_database.py
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///./data/argentina.db
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ENABLE_REAL_DATA
        value: true
      - key: CORS_ORIGINS
        value: '["https://argfy.vercel.app", "https://*.vercel.app", "http://localhost:3000"]'
    healthCheckPath: /health
    autoDeploy: true
