version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/argentina.db
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend/data:/app/data
    depends_on:
      - db
    networks:
      - argfy-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
      - NEXT_PUBLIC_API_BASE=http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - argfy-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=argfy
      - POSTGRES_USER=argfy
      - POSTGRES_PASSWORD=argfy123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - argfy-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - argfy-network

volumes:
  postgres_data:
  redis_data:

networks:
  argfy-network:
    driver: bridge